name: tests

on:
  push:
    branches-ignore: [gh-pages]
  pull_request:
    branches-ignore: [gh-pages]
  schedule:
    - cron: '0 0 * * 1'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        nimversion:
        - stable
        - devel
        os:
        - ubuntu-latest
        - macOS-latest
        - windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: iffy/install-nim@v1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        nimversion: ${{ matrix.nimversion }}
    - name: Test
      continue-on-error: ${{ matrix.nimversion == "devel" }}
      run: |
        nimble test
        nimble refresh
    - name: Docs
      if: runner.os == 'Linux'
      run: |
        ./builddocs.sh
