name: tests

on:
  push:
    branches-ignore: [gh-pages]
  schedule:
    - cron: '0 0 * * 1'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        nimversion: [stable, devel]
        os:
        - ubuntu-latest
        - macOS-latest
        - windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache nimble
      if: runner.os != 'Windows'
      id: cache-nimble
      uses: actions/cache@v1
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
    - uses: jiro4989/setup-nim-action@v1
      with:
        nimversion: ${{ matrix.nim-version }}
    - name: Test
      run: |
        nimble test
        nimble refresh
    - name: Docs
      if: runner.os == 'Linux'
      run: |
        ./builddocs.sh
